stages:
  - deploy

deploy_docker_all:
    stage: deploy
    environment: production
    script:
        - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then TAG="latest"; else TAG="$CI_COMMIT_REF_NAME"; fi
        - if [ "$CI_PROJECT_NAMESPACE" = "anduin" ]; then HUB_NAMESPACE="anduin2019"; else HUB_NAMESPACE="$CI_PROJECT_NAMESPACE"; fi
        
        # Build once
        - LOCAL_IMAGE="$CI_PROJECT_NAME:$TAG"
        - echo "Building Docker image $LOCAL_IMAGE..."
        - docker build . -t $LOCAL_IMAGE
        
        # Push to hub.aiursoft.com
        - echo "Pushing to hub.aiursoft.com..."
        - TARGET="hub.aiursoft.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG"
        - docker tag $LOCAL_IMAGE $TARGET
        - echo "$LOCAL_DOCKER_PASSWORD" | docker login hub.aiursoft.com -u "$LOCAL_DOCKER_USERNAME" --password-stdin
        - docker save $TARGET -o temp.tar
        - regctl image import $TARGET temp.tar
        - rm ./temp.tar
        
        # Push to hub.aiursoft.cn
        - echo "Pushing to hub.aiursoft.cn..."
        - TARGET="hub.aiursoft.cn/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG"
        - docker tag $LOCAL_IMAGE $TARGET
        - echo "$CN_DOCKER_PASSWORD" | docker login hub.aiursoft.cn -u "$CN_DOCKER_USERNAME" --password-stdin
        - docker save $TARGET -o temp.tar
        - regctl image import $TARGET temp.tar
        - rm ./temp.tar
        
        # Push to Docker Hub
        - echo "Pushing to Docker Hub..."
        - TARGET="$HUB_NAMESPACE/$CI_PROJECT_NAME:$TAG"
        - docker tag $LOCAL_IMAGE $TARGET
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $TARGET
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          exists:
              - Dockerfile
